### ISSUE TITLE
Add new metrics for generator evaluation ‘SEMSCORE'

### ISSUE THREAD

**Issue by vkehfdl1** [Marker-Inc-Korea/AutoRAG#154]
[paper](https://arxiv.org/pdf/2401.17072.pdf)

### Overview
SemScore is a simple metric. Just embeds generate ground truth and model’s generation, and calculates cosine similarity.

Even it is quite simple, correlation with human evaluation and SemScore evaluation is quite high comparing between other evaluation scores. 
We knew that traditional generation evaluation metrics are quite bad. This can be the great solution for us.  

## To-do list
- [x] add [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) embedding to support embedding models
- [x] Get metrics via dictionary with their options. Enabling this will solve the issue #44 either.
- [x] Make SemScore metrics. Default embedding model will be ‘all-mpnet-base-v2’, but I’m sure other embdding model can be effective.
- [x] Make documentation for this metric. (We don’t have documentation for selecting rigth strategy for each module)
